# Generated by Django 4.0 on 2021-12-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=14)),
                ('ano_escolar', models.CharField(choices=[('9° Ano', '9° Ano'), ('8° Ano', '8° Ano'), ('7° Ano', '7° Ano'), ('6° Ano', '6° Ano'), ('5° Ano', '5° Ano'), ('4° Ano', '4° Ano'), ('3° Ano', '3° Ano'), ('2° Ano', '2° Ano'), ('1° Ano', '1° Ano'), ('1° Ano Médio', '1° Ano Médio'), ('2° Ano Médio', '2° Ano Médio'), ('3° Ano Médio', '3° Ano Médio')], default='1° Ano', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=14)),
                ('materia', models.CharField(max_length=50)),
            ],
        ),
    ]
